### ISSUE TITLE
Not working11!!!!11!

### ISSUE THREAD

**Issue by GizmoTjaz** [Hotvinyl6347/gizmopy#1]
Everytime I make a request I get this output:

`{ "output": { "error": "Python sucks" } }`

fix?!?!?! pls?!?!

**Comment by GizmoTjaz** [comment]
helllo deve pls fixa!!!!

**Comment by shirokoneko** [comment]
suck my dick you homeless bastard

**Comment by GizmoTjaz** [comment]
The problem is that you're using Python

**Comment by shirokoneko** [comment]
Fuck you bitch 

Fuck off
